const data=[['PKJ-2026-0031','Pemohon A','2026-10-02','07:00','Seremban','Tunggu',true,'Menunggu Semakan'],['PKJ-2026-0030','Pemohon B','2026-10-03','08:00','Kuala Lumpur','Tidak Tunggu',true,'Menunggu Kelulusan'],['PKJ-2026-0029','Pemohon C','2026-10-04','09:00','Shah Alam','Tunggu',true,'Diluluskan'],['PKJ-2026-0028','Pemohon D','2026-10-05','07:30','Putrajaya','Tidak Tunggu',true,'Diluluskan'],['PKJ-2026-0027','Pemohon E','2026-10-01','08:00','Melaka','Tunggu',false,'Menunggu Semakan']];
const rows=document.querySelector('#rows'), status=document.querySelector('#status'), need=document.querySelector('#need'), search=document.querySelector('#search');
function cls(s){return s==='Diluluskan'?'approved':s==='Menunggu Kelulusan'?'review':'pending'}
function render(){let q=search.value.toLowerCase();rows.innerHTML=data.filter(x=>(!q||x.join(' ').toLowerCase().includes(q))&&(!status.value||x[7]===status.value)&&(!need.value||x[5]===need.value)).map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${new Date(x[2]).toLocaleDateString('ms-MY')}<br>${x[3]}</td><td>${x[4]}</td><td><span class="badge wait">${x[5]}</span></td><td>${x[6]?'🟢 Ada':'🔴 Tiada'}</td><td><span class="badge ${cls(x[7])}">${x[7]}</span></td></tr>`).join('')}
[search,status,need].forEach(x=>x.addEventListener('input',render));[status,need].forEach(x=>x.addEventListener('change',render));
const modal=document.querySelector('#modal');newBtn.onclick=()=>modal.classList.remove('hidden');close.onclick=()=>modal.classList.add('hidden');cancel.onclick=()=>modal.classList.add('hidden');
const d=new Date();d.setDate(d.getDate()+1);tripDate.min=d.toISOString().slice(0,10);
let pn=0,en=0;addPassenger.onclick=()=>{pn++;passengers.insertAdjacentHTML('beforeend',`<tr><td>${pn}</td><td><input required></td><td><input></td><td><input></td><td><input></td><td><input></td><td><button type="button" class="remove" onclick="this.closest('tr').remove()">×</button></td></tr>`)};
addEquipment.onclick=()=>{en++;equipment.insertAdjacentHTML('beforeend',`<tr><td>${en}</td><td><input></td><td><input type="number" min="1"></td><td><input></td><td><input></td><td><button type="button" class="remove" onclick="this.closest('tr').remove()">×</button></td></tr>`)};
letter.onchange=e=>{if(e.target.files[0])fileText.textContent='✓ '+e.target.files[0].name};
form.onsubmit=e=>{e.preventDefault();if(!letter.files.length)return toast('Surat arahan tugas rasmi wajib dilampirkan.');if(tripDate.value<tripDate.min)return toast('Tarikh perjalanan perlu sekurang-kurangnya satu hari lebih awal.');toast('Permohonan berjaya direkodkan untuk semakan.');modal.classList.add('hidden');form.reset();fileText.textContent='Kepilkan surat arahan tugas rasmi'};
function toast(x){const t=document.querySelector('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}render();
